name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      node-version:
        required: false
        default: "22.x"

# Only one pull-request triggered run should be executed at a time
# (head_ref is only set for PR events, otherwise fallback to run_id which differs for every run).
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install project
        run: |
          npm install

      - name: Run tests
        run: |
          npm run test


